### ISSUE TITLE
devscripts: Dependency `sensible-utils` changed its name

### ISSUE THREAD

**Issue by babolivier** [ItachiSan/linux_packaging#14] opened 2023-04-22 21:42 UTC
Earlier this month, `sensible-utils` has been renamed into `sensible-utils-data`: https://aur.archlinux.org/packages/sensible-utils-data#comment-909595

This means the `devscript` package cannot be installed anymore:

```
[22:38:12] brendan@Noah:~$ yay devscripts
2 aur/devscripts-git 2.16.13.r2.gbce34b8d-1 (+0 0.00) (Out-of-date: 2022-09-21) 
    Scripts to make the life of a Debian Package maintainer easier (git-latest)
1 aur/devscripts 2.23.4-1 (+27 0.01) 
    Scripts to make the life of a Debian Package maintainer easier
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==> 1
 -> No AUR package found for sensible-utils
 -> could not find all required packages: sensible-utils 
[22:38:21] brendan@Noah:~$

**Comment by xiota** [comment] 2023-04-27 05:29
`sensible-utils` is a now a base package that creates `sensible-pager`, `sensible-editor`, `sensible-browser`, and `sensible-utils-data`.  

`devscripts` builds without `sensible-utils`.  Don't know what functionality is affected.  Users who want/need `sensible-*` can install them separately.

**Comment by ctrlcctrlv** [comment] 2023-05-27 15:08
Sorry for the name change. Please advise what I could possibly do to make it easier on this package. (I maintain AUR pkgbase sensible-utils).

**Comment by ctrlcctrlv** [comment] 2023-05-27 15:09
Indeed @xiota is right, perhaps I can add a metapackage requiring all of those.

**Comment by xiota** [comment] 2023-05-27 15:30
If `sensible-*` are not actually needed to use `devscripts`, they should be removed from dependencies or moved to optdepends, annotated with what additional functionality they provide.

**Comment by xiota** [comment] 2023-05-27 15:34
A metapackage would reduce the disruption caused by the packaging change, but I wonder what the point of the change was in the first place.  Is there really a need or desire to install them separately from each other?  If people would use/prefer a metapackage anyway, why split them?

**Comment by ctrlcctrlv** [comment] 2023-05-27 15:55
Works for me.

```
[fred@デブ狸 ~/Workspace/aur/sensible-utils]$ pacman -Qi sensible-utils

Name            : sensible-utils
Version         : 0.0.17-4
Description     : Utilities for sensible alternative selection (stub metapackage)
Architecture    : any
URL             : http://packages.debian.org/source/sid/sensible-utils
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : bash  sensible-pager  sensible-editor  sensible-browser  sensible-utils-data
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 2.00 B
Packager        : Fredrick R. Brennan <copypaste@kittens.ph>
Build Date      : Sat 27 May 2023 11:53:59 AM EDT
Install Date    : Sat 27 May 2023 11:55:17 AM EDT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

Will push.

**Comment by ctrlcctrlv** [comment] 2023-05-27 17:35
I think there is as `sensible-pager` requires the highly disruptive script `/usr/bin/pager` to work.

**Comment by ctrlcctrlv** [comment] 2023-05-27 17:37
Furthermore, the package is unlikely to ever be installed as a choice by users, see: this entire issue.

Allowing other AUR maintainers to say _why_ they want `sensible-utils` (i.e. what in the package requires it) reduces end-user problems.

**Comment by ItachiSan** [comment] 2023-06-18 20:44
Hi @babolivier , @xiota and @ctrlcctrlv.
Sorry for the very long silence, but life happened in multiple ways.

So, I am a bit unsure on what to do, since this:
https://salsa.debian.org/debian/devscripts/-/blob/master/debian/control#L88
seems to be a normal dependency and not a build one.

I would then think to use the metapackage rather than just the *-data* one.

If I am incorrect, please mention it so that I can switch to the data only variant :smile:

**Comment by xiota** [comment] 2023-06-18 22:26
A new maintainer took over `aur/sensible-utils` and split the package so that each component basically installs a single script.  This broke every package that depended on the original `sensible-utils`.  The `-data` package is insufficient to satisfy dependencies for `devscripts`.  You would have to examine the scripts within `devscripts` to see which individual components of the split package are needed.

I created `sensible-utils-unified` that restores the original `sensible-utils` to fix the broken packages.  However, the maintainer of the split package immediately opened a deletion request against it.  I do recommend making `sensible-utils` optional in case the deletion request is approved.  That way, `devscripts` will remain buildable/installable, even if some functionality is absent.  Alternatively, you can depend on `sensible-utils-unified`, which *might* protect against issues with the split package.

**Comment by eclairevoyant** [comment] 2023-06-18 23:50
@ItachiSan It needs to depend on `sensible-browser` and `sensible-editor` since that is [what is used in the scripts](https://salsa.debian.org/search?group_id=2&nav_source=navbar&project_id=18475&repository_ref=master&search=sensible&search_code=true)

**Comment by xiota** [comment] 2023-06-19 01:28
That is what the devscripts use, for now.  You would have to keep a closer eye on upstream changes to update dependencies if other sensible- components are used.  The maintainer of the split package has also missed some upstream changes that particularly affect split packaging.

**Comment by ItachiSan** [comment] 2023-06-20 07:08
As of:
https://aur.archlinux.org/cgit/aur.git/commit/?h=devscripts&id=bbcceed7d613ff943961a8237636dd728d1efd9c
the proper dependencies are matched.
Let me know if that is enough :smile:

**Comment by eclairevoyant** [comment] 2023-06-20 16:41
lgtm, we should be able to close this

**Comment by ItachiSan** [comment] 2023-06-25 12:45
Closing the issue given the changes, comment here if not enough and I will reopen it :wink:

**Closed as completed by ItachiSan** 2023-06-25 12:45 UTC
